### ISSUE TITLE
Request for permission to adopt this script use in Module TeamsFunctions

### ISSUE THREAD

**Issue by DEberhardt** [MCSMLab/Activate-PimRoles#2]
Hello,

I was wondering whether I could get your permission to use this wonderful script to add it to `Connect-Me` - my take on Connection to SkypeOnline, AzureAd and MicrosoftTeams in one go and whether I could integrate the PIM role activation into it.

Full credit where credit is due of course 👍 

Cheers,
David

PS: https://github.com/DEberhardt/TeamsFunctions

**Comment by MCSMLab** [comment]
I'm fine with that, but this script no longer works since Microsoft changed the PIM PowerShell commands. I'll rewrite this script once the new PIM PowerShell cmdlets go GA.

**Comment by DEberhardt** [comment]
Excellent. I have, in the meanwhile, worked with your script as a blueprint and created [Enable-AzureAdAdminRole](https://github.com/DEberhardt/TeamsFunctions/blob/dev/Public/Functions/UserAdmin/Enable-AzureAdAdminRole.ps1)

It does what it should, but is currently lacking two things:
- A choice for activating individual roles
- Support for Privileged Admin Groups

Now working on those over the coming days and faster query for Admin Roles ([Get-AzureAdAssignedAdminRoles](https://github.com/DEberhardt/TeamsFunctions/blob/dev/Public/Functions/UserAdmin/Get-AzureAdAssignedAdminRoles.ps1) is quite slow

**Comment by MCSMLab** [comment]
Nice. I’ll take a look next week and see what I can do.

I’ve been meaning to update that script, but haven’t gotten around to it yet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DEberhardt** [comment]
Added confirmation with ShouldProcess and Force (=EnableAll)
Now well rouneded, just the PAG integration is missing still (issue pending with DOCs team
https://github.com/MicrosoftDocs/azure-docs/issues/68100
